// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCak0gWp0-xg4Fb6H4jdkyFYWGIpZ2l97s',
    appId: '1:909562978336:android:64b0634327a91ca1681c45',
    messagingSenderId: '909562978336',
    projectId: 'crm-gt-39eb3',
    storageBucket: 'crm-gt-39eb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQSSJFNU-loAW0uemrfenlKuiVFvsdYuc',
    appId: '1:909562978336:ios:11397bb7f0d5b272681c45',
    messagingSenderId: '909562978336',
    projectId: 'crm-gt-39eb3',
    storageBucket: 'crm-gt-39eb3.firebasestorage.app',
    iosBundleId: 'com.gt.crm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkhlYJOWyU1mYRdRkfSMPH_vnQXs7puCg',
    appId: '1:909562978336:web:dde83c8bbf083856681c45',
    messagingSenderId: '909562978336',
    projectId: 'crm-gt-39eb3',
    authDomain: 'crm-gt-39eb3.firebaseapp.com',
    storageBucket: 'crm-gt-39eb3.firebasestorage.app',
    measurementId: 'G-Q9L45PT0H0',
  );
}
